#########################################################
#
# MMA_LOCAL API
#
#########################################################


@local=http://192.168.0.163:9090


########################################################
### VERSION INFO
get {{local}}/version

########################################################
### 트랜젝션 가스 수수료 계산
post {{local}}/info/gasfee

{
    "gasLimit" : 21000
}

########################################################
### 스케줄러 마스터/가스비 지갑 정보
get {{local}}/v1/info/master



########################################################
### 회원가입
post {{local}}/v1/sign

{
    "name" : "tester_05"
}



#########################################################
### DEFINE_SECTION
#########################################################
@token_symbol=WNZ

@user_name=tester_01
@user_uid=1001
@user_address=0xf811b879b9f4f24b411a92ebd10dfb7e79c4a200

@out_address=0x8CE5bb2013887eD586e6a87211aa126453368b7A



########################################################
### 유저정보
get {{local}}/v1/info/member/name/{{user_name}}

###
get {{local}}/v1/info/member/uid/{{user_uid}}

###
get {{local}}/v1/info/member/address/{{user_address}}

### 유저정보 (CBC_KEY_
get {{local}}/v1/info/pk/name/{{user_name}}



########################################################
### [ 코인 출금 ] 현재 코인 출금을 위한 대기열 갯수
get {{local}}/v1/withdraw/waitings



########################################################
### [ 코인 출금 요청 ] 코인 출금 요청
post {{local}}/v1/withdraw/try

{
    "name" : "{{user_name}}",
    "from_address" : "{{user_address}}",
    "symbol" : "{{token_symbol}}",
    "price" : "0.1",
    "to_address" : "{{out_address}}"
}


########################################################
### [ 코인 출금 결과 ] 코인 출금 결과
get {{local}}/v1/withdraw/result/receipt_5688dbd84e91a0540a82da4ee20131e3f4e4107c


########################################################
### 개인지갑에서 직접 출금을 위한 ( 잔액조회 및 가스비 계산)
post {{local}}/v1/user/withdraw_info

{
    "from_address" : "{{user_address}}",
    "symbol" : "{{token_symbol}}",
    "price" : "0.1",
    "to_address" : "{{out_address}}"
}

########################################################
### 개인지갑에서 직접 출금 신청
post {{local}}/v1/user/withdraw_try

{
    "from_address" : "{{user_address}}",
    "symbol" : "{{token_symbol}}",
    "price" : "0.1",
    "to_address" : "{{out_address}}"
}

########################################################
### 개인지갑 출금신청 결과 확인 요청
get {{local}}/v1/user/withdraw_result/self_ea805319906edf70bcf42081ce8dadac0c8b3



########################################################
### MASTER SECTION
########################################################



########################################################
### [ 마스터지갑에서 외부 지갑주소로 출금시 트랜잭션 수수료 예측 ]
get {{local}}/v1/estimate/master/tx_fee



########################################################
### [ 마스터출금 ] 마스터 계좌에서 외부계좌로 출금신청
post {{local}}/v1/master/out/try

{
    "symbol" : "{{token_symbol}}",
    "price" : "0.5",
    "to" : "{{out_address}}"
}



########################################################
### [ 마스터출금 ] 마스터 계좌에서 외부계좌로 출금신청
get {{local}}/v1/master/out/result/master_6081554244327977080











