#########################################################
#
# MMA_LOCAL ADMIN
#
#########################################################


@local=http://192.168.0.163:9090



########################################################
### [ 정보 ] 마스터 지갑 정보
get {{local}}/v2/info/master
Txm-Adn-Tk:spear



########################################################
### [ 마스터송금 ] 입금계좌에서 마스터로 재화 전송 (ROOT 권한) 
post {{local}}/v2/deposit_to_master/one
Txm-Adn-Tk:spear

{
    "uid" : 1001,
    "symbol" : "ETH"
}


########################################################
###     



######

get https://etherscan.io/address/0xa7b1F64b3F63d726467940a040542A3bDF3AcAC9 